### PR TITLE
Options to decide what type of non-advective cells are fixed/checked

### PR DESCRIPTION
**Pull request by micaeljtoliveira**
Add a couple of options to decide what type of non-advective cells are fixed/checked.

### CODE REVIEW

**Comment by micaeljtoliveira** [comment]
@aekiss If you have some time, maybe you could have a look at this and tell me if it makes sense? It's also a good opportunity to get familiar with how these utilities look like here.

**Comment by aekiss** [comment]
I'll try to get onto this tomorrow

**Comment by micaeljtoliveira** [comment]
No worries, it's not urgent at all.

**Review by aekiss — APPROVED** [review]
LGMT - thanks!

**Pull request merged**
